- name: Ensure secret tools are installed
  ansible.builtin.package:
    name:
      - keepassxc
    state: present
  register: pkg_result
- name: Display package installation result
  ansible.builtin.debug:
    var: pkg_result
