- name: Ensure Fish Shell is installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - fish
  register: pkg_result
  failed_when: false

- name: Display package installation result
  ansible.builtin.debug:
    var: pkg_result


- name: Ensure Shell plugins are installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - atuin
    - fzf
    - zoxide
    - asciinema
    - bat
    - btop
    - ccze
    - htop
  register: pkg_result
  failed_when: false

- name: Display package installation result
  ansible.builtin.debug:
    var: pkg_result
