- name: Ensure Fish Shell is installed
  ansible.builtin.package:
    name:
      - fish
    state: present
  register: pkg_result

- name: Ensure Shell plugins are installed
  ansible.builtin.package:
    name:
      - ShellCheck
      - atuin
      - fzf
      - zoxide
      - asciinema
      - bat
      - btop
      - ccze
      - htop
    state: present
  register: pkg_result

- name: Display package installation result
  ansible.builtin.debug:
    var: pkg_result
