- name: Ensure Editors are installed
  ansible.builtin.package:
    name:
      - vim
      - vim-minimal
      - vim-enhanced
    state: present
  register: pkg_result

- name: Display package installation result
  ansible.builtin.debug:
    var: pkg_result


- name: Add Microsoft VS Code repository
  ansible.builtin.yum_repository:
    name: vscode
    description: Visual Studio Code
    file: vscode
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: 1
    gpgkey:
      - https://packages.microsoft.com/keys/microsoft.asc
  when: "'microsoft' not in ansible_kernel | lower"

  register: yum_add_result
- name: Display repository addition result
  ansible.builtin.debug:
    var: yum_add_result

- name: Ensure VS Code is installed
  ansible.builtin.package:
    name:
      - code
    state: present
  register: pkg_result
  when: "'microsoft' not in ansible_kernel | lower"
- name: Display package installation result
  ansible.builtin.debug:
    var: pkg_result

- name: Where is code
  become: true
  become_user: "{{ principaluser }}"
  ansible.builtin.shell: |
    source ~/.profile 2>/dev/null || true
    source ~/.bashrc 2>/dev/null || true
    command -v code
  args:
    executable: /bin/bash -l
  register: vscode_code_path
  changed_when: false
  failed_when: false


- name: Check vscode Extensions
  become: true
  become_user: "{{ principaluser }}"
  ansible.builtin.command: code --list-extensions
  register: vscode_installed_extensions
  changed_when: false
  when: vscode_code_path.stdout != ""

- name: Install vscode Extensions
  become: true
  become_user: "{{ principaluser }}"
  ansible.builtin.shell: |
    source ~/.
    code --install-extension {{ item }}
  args:
    executable: /bin/bash
  loop:
    - clutchsecurity.clutch-gitleaks-secrets-scanner
    - docker.docker
    - dotjoshjohnson.xml
    - dqisme.sync-scroll
    - esbenp.prettier-vscode
    - ffaraone.opensslutils
    - github.copilot
    - github.copilot-chat
    - github.vscode-github-actions
    - m4ns0ur.base64
    - mechatroner.rainbow-csv
    - mhutchie.git-graph
    - michalhajny.kustomize-navigator
    - mindaro-dev.file-downloader
    - mindaro.mindaro
    - ms-azuretools.vscode-containers
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.kind-vscode
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - ms-python.debugpy
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-python.vscode-python-envs
    - ms-vscode.makefile-tools
    - ms-vscode.remote-explorer
    - ms-vscode-remote.remote-containers
    - ms-vscode-remote.remote-ssh
    - ms-vscode-remote.remote-ssh-edit
    - nogic.nogic
    - oas2tree.oas2tree
    - opentofu.vscode-opentofu
    - pkief.material-icon-theme
    - redhat.ansible
    - redhat.vscode-yaml
    - sandipchitale.vscode-kubernetes-edit-kubeconfig
    - shakram02.bash-beautify
    - shd101wyy.markdown-preview-enhanced
    - timonwong.shellcheck
  when: vscode_code_path.stdout != "" and item not in vscode_installed_extensions.stdout
  async: 30
  poll: 5
  register: result
  ignore_errors: true

- name: Verification
  ansible.builtin.debug:
    msg: "Network Error or verify extension"
  when: result is failed

- name: Ensure yq/jq are installed
  ansible.builtin.package:
    name:
      - yq
      - jq
    state: present
  register: pkg_result

- name: Display package installation result
  ansible.builtin.debug:
    var: pkg_result

- name: Ensure meld diff tool is installed
  ansible.builtin.package:
    name:
      - meld
    state: present
  register: pkg_result

- name: Display package installation result
  ansible.builtin.debug:
    var: pkg_result
