---
- name: Standard Configuration
  hosts: localhost
  gather_facts: true
  become_method: ansible.builtin.sudo
  become: true
  roles:
    - commons
    - dotfiles
    - shell
    - networkutils
    - editors
    - cloudutils
    - filemanagers
    - gitcli
