- name: Ensure Dotfiles tools are installed
  ansible.builtin.package:
    name:
      - chezmoi
    state: present
  register: pkg_result
- name: Display package installation result
  ansible.builtin.debug:
    var: pkg_result

- name: Initialize chezmoi if not already
  become: true
  become_user: "{{ principaluser }}"
  ansible.builtin.command: chezmoi init "{{ dotfiles_repo }}"
  args:
    creates: "/home/{{ principaluser }}/.local/share/chezmoi"
  when: dotfiles_repo | length > 0

- name: Pull dotfiles repository
  become: true
  become_user: "{{ principaluser }}"
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "/home/{{ principaluser }}/.local/share/chezmoi"
    register: git_result
  when: dotfiles_repo | length > 0
  changed_when: git_result.changed

- name: Display git result
  ansible.builtin.debug:
    var: git_result

- name: Check chezmoi diff
  become: true
  become_user: "{{ principaluser }}"
  ansible.builtin.command: chezmoi diff
  register: chezmoi_diff
  changed_when: false
  failed_when: false
  when: dotfiles_repo | length > 0

- name: Apply dotfile safely
  become: true
  become_user: "{{ principaluser }}"
  ansible.builtin.command: chezmoi apply --safe
  when:
    - dotfiles_repo | length > 0
    - chezmoi_diff.stdout | length != 0
  async: 30
  poll: 5
  register: result
  ignore_errors: true

- name: Verification
  ansible.builtin.debug:
    msg: "Verify and sync dotfiles manually, timeout reached"
  when:
    - dotfiles_repo | length > 0
    - result is failed

