- name: Ensure commons are installed
  ansible.builtin.package:
    name:
      - openssl
    state: present
  register: pkg_result
- name: Display package installation result
  ansible.builtin.debug:
    var: pkg_result