- name: Ensure NetTools are installed
  ansible.builtin.package:
    name:
      - ipcalc
      - subnetcalc
      - net-tools
      - nmap
    state: present
  register: pkg_result

- name: Display package installation result
  ansible.builtin.debug:
    var: pkg_result

- name: Sync fortheducksakeproxyswitch
  become_user: "{{ principaluser }}"
  ansible.builtin.git:
    repo: https://github.com/uduwat/fortheducksakeproxyswitch.git
    dest: "/home/{{ principaluser }}/.fortheducksakeproxyswitch"
  register: gitresult

- name: Show fortheducksakeproxyswitch results
  ansible.builtin.debug:
    var: gitresult