- name: Max_user_watches
  ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: '1048576'
    sysctl_set: true
    state: present
    reload: true

- name: Max_user_instances
  ansible.posix.sysctl:
    name: fs.inotify.max_user_instances
    value: '8192'
    sysctl_set: true
    state: present
    reload: true
