- name: Add Google Cloud CLI repository
  ansible.builtin.yum_repository:
    name: gcp-cli
    description: Google Cloud CLI
    file: google-cloud-sdk
    baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el9-x86_64
    gpgcheck: 1
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  register: yum_add_result
- name: Display repository addition result
  ansible.builtin.debug:
    var: yum_add_result

- name: Ensure GCP CLI is installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - google-cloud-cli
    - google-cloud-cli-gke-gcloud-auth-plugin
  register: pkg_result
  failed_when: false
- name: Display package installation result
  ansible.builtin.debug:
    var: pkg_result


- name: Add Kubectl repository
  ansible.builtin.yum_repository:
    name: kubectl
    description: Kubectl
    file: kubectl
    baseurl: https://pkgs.k8s.io/core:/stable:/v1.36/rpm/
    gpgcheck: 1
    gpgkey:
      - https://pkgs.k8s.io/core:/stable:/v1.36/rpm/repodata/repomd.xml.key

  register: yum_add_result
- name: Display repository addition result
  ansible.builtin.debug:
    var: yum_add_result

- name: Ensure kubectl is installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - kubectl
  register: pkg_result
  failed_when: false
- name: Display package installation result
  ansible.builtin.debug:
    var: pkg_result

- name: Ensure Kubernetes TUI/GUI tools are installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - k9s
    - freelens
  register: pkg_result
  failed_when: false
- name: Display package installation result
  ansible.builtin.debug:
    var: pkg_result


- name: Create kubeconfig ~/.kube/configs per principal user
  ansible.builtin.file:
    path: "/home/{{ principaluser }}/.kube/configs"
    state: directory
    owner: "{{ principaluser }}"
    group: "{{ principaluser }}"
    mode: '0755'
  become: true

- name: Sync k9s plugins
  become_user: "{{ principaluser }}"
  ansible.builtin.git:
    repo: https://github.com/GDClouders/Awesome-k9s-Plugins.git
    dest: "/home/{{ principaluser }}/.Awesome-k9s-Plugins"
  register: gitresult

- name: Show k9s plugins results
  ansible.builtin.debug:
    var: gitresult

- name: Apply k9s plugins
  ansible.builtin.copy:
    src: "/home/{{ principaluser }}/.Awesome-k9s-Plugins/plugins/"
    dest: "/home/{{ principaluser }}/.config/k9s/plugins/"
    mode: "0644"
  when: gitresult.before != gitresult.after

- name: Apply dumb plugin file
  ansible.builtin.copy:
    src: "/home/{{ principaluser }}/.Awesome-k9s-Plugins/plugins.yaml"
    dest: "/home/{{ principaluser }}/.config/k9s/plugins.yaml"
    mode: "0644"
  when: gitresult.before != gitresult.after

- name: Check if krew is already installed
  become_user: "{{ principaluser }}"
  stat:
    path: "/home/{{ principaluser }}/.krew/bin/kubectl-krew"
  register: krew_bin

- name: Create temp directory
  become_user: "{{ principaluser }}"
  file:
    path: /tmp/krew_install
    state: directory
    mode: '0755'
  when: not krew_bin.stat.exists

- name: Detect OS
  set_fact:
    krew_os: "{{ ansible_system | lower }}"
  when: not krew_bin.stat.exists

- name: Detect ARCH
  set_fact:
    krew_arch: >-
      {% if ansible_architecture == "x86_64" %}
        amd64
      {% elif ansible_architecture in ["aarch64", "arm64"] %}
        arm64
      {% elif ansible_architecture is match("arm.*") %}
        arm
      {% else %}
        {{ ansible_architecture }}
      {% endif %}
  when: not krew_bin.stat.exists

- name: Set package name
  set_fact:
    krew_pkg: "krew-{{ krew_os }}_{{ krew_arch }}"
  when: not krew_bin.stat.exists

- name: Download krew
  become_user: "{{ principaluser }}"
  get_url:
    url: "https://github.com/kubernetes-sigs/krew/releases/latest/download/{{ krew_pkg }}.tar.gz"
    dest: "/tmp/krew_install/{{ krew_pkg }}.tar.gz"
  when: not krew_bin.stat.exists

- name: Extract archive
  become_user: "{{ principaluser }}"
  unarchive:
    src: "/tmp/krew_install/{{ krew_pkg }}.tar.gz"
    dest: "/tmp/krew_install"
    remote_src: yes
  when: not krew_bin.stat.exists

- name: Install krew
  become_user: "{{ principaluser }}"
  command: "./{{ krew_pkg }} install krew"
  args:
    chdir: "/tmp/krew_install"
  environment:
    KREW_ROOT: "/home/{{ principaluser }}/.krew"
  when: not krew_bin.stat.exists


- name: Ensure PATH for current session
  become_user: "{{ principaluser }}"
  set_fact:
    krew_path: "{{ principaluser }}/.krew/bin:{{ ansible_env.PATH }}"

# ---- Plugin install ----

- name: Update krew index
  become_user: "{{ principaluser }}"
  command: "/home/{{ principaluser }}/.krew/bin/kubectl-krew update"
  # environment:
  #   PATH: "{{ krew_path }}"
  changed_when: false

- name: Add custom krew indexes
  become: yes
  become_user: "{{ principaluser }}"
  environment:
    PATH: "{{ krew_path }}"
  loop:
    - { name: kvaps, url: "https://github.com/kvaps/krew-index" }
    - { name: kor, url: "https://github.com/yonahd/krew-index" }
    - { name: retina, url: "https://github.com/microsoft/retina" }
  command: "/home/{{ principaluser }}/.krew/bin/kubectl-krew index add {{ item.name }} {{ item.url }}"
  register: add_index
  failed_when: false
  changed_when: "'Added' in add_index.stdout"


- name: Install krew plugins
  become_user: "{{ principaluser }}"
  command: "/home/{{ principaluser }}/.krew/bin/kubectl-krew install {{ item }}"
  # environment:
  #   PATH: "{{ krew_path }}"
  loop: 
    - krew
    - blame
    - cnf
    - crd-wizard
    - df-pv
    - exec-as
    - flame
    - kor
    - kvaps/node-shell
    - neat
    - oidc-login
    - oomd
    - pod-lens
    - retina
    - stern
    - virt
  register: plugin_install
  failed_when: false
  changed_when: "'Installed' in plugin_install.stdout"

# ---- Cleanup ----

- name: Cleanup temp dir
  become_user: "{{ principaluser }}"
  file:
    path: /tmp/krew_install
    state: absent
  when: not krew_bin.stat.exists
